### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.xiphos.Xiphos#2]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by nedrichards** [comment]
[The appdata](https://github.com/crosswire/xiphos/blob/master/xiphos.appdata.xml), from upstream, has screenshots. Are you seeing issues?

**Comment by LeandroStanger** [comment]
@nedrichards 
![captura de tela de 2017-12-03 21-41-42](https://user-images.githubusercontent.com/26097419/33531331-ce268a1a-d872-11e7-9458-ffc811a78030.png)
