### ISSUE TITLE
Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.xiphos.Xiphos#3]
[eos-diagnostic-171203_100350_UTC-0200.txt](https://github.com/flathub/org.xiphos.Xiphos/files/1524719/eos-diagnostic-171203_100350_UTC-0200.txt)
[eos-diagnostic-171203_100613_UTC-0200.txt](https://github.com/flathub/org.xiphos.Xiphos/files/1524720/eos-diagnostic-171203_100613_UTC-0200.txt)

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Erro do GConf: Falha ao ativar servidor de configuração: org.freedesktop.DBus.Error.ServiceUnknown

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by nedrichards** [comment]
Fixed in https://github.com/flathub/org.xiphos.Xiphos/commit/74574044f42cb8c15cd04536f2d84d283cffe3a6 (you'll get a different error on Endless OS - but it doesn't matter)
